#Private pod Specs
#source 'https://github.com/druva/dPodSpecs.git'

# Uncomment this line to define a global platform for your project
 platform :ios, '11.0'

# Uncomment this line if you're using Swift
use_frameworks!

target 'ViniTestPod' do
    #pod 'dSwiftUtils',:path => '/Volumes/DriveA/Code/Personal/dSwiftUtils'
    #pod 'dSwiftUtils','>= 0.2.5'
    pod 'dSwiftUtils',:path => './'
    #pod 'SwiftUtils'
end