#Private pod Specs
#source 'https://github.com/druva/dPodSpecs.git'

# Uncomment this line to define a global platform for your project
 platform :ios, '11.0'

# Uncomment this line if you're using Swift
use_frameworks!

target 'ViniTestPod' do
    #pod 'dSwiftUtils',:path => '/Volumes/DriveA/Code/Personal/dSwiftUtils'
    #pod 'dSwiftUtils','>= 0.2.5'
    pod 'ViniTestPod',:path => './'
    pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'rxswift4.0-swift4.0'
    #pod 'SwiftUtils'
end